# Site settings
markdown: kramdown
pygments: true
highlighter: pygments
permalink: /:year/:month/:day/:title.html
title: Someone like me
email: hongdinggao@gmail.com


description: A beautiful blog that is beautiful
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://hongdinggao.github.io" 
#twitter_username: jekyllrb
github_username:  hongdinggao


navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://foto.lhzhang.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml