# Site settings
markdown: kramdown
pygments: true
highlighter: rouge
permalink: /:year/:month/:day/:title.html
title: Hongding Gao
email: hongdinggao@gmail.com
description: A Minimalist and bastard
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://hongdinggao.github.io" 


github_username:  hongdinggao

theme: jekyll-theme-minimal