# Site settings
markdown: kramdown
pygments: true
highlighter: pygments
permalink: /:year/:month/:day/:title.html
title: Someone like me
email: hongdinggao@gmail.com


description: A beautiful blog that is beautiful
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://hongdinggao.github.io" 
#twitter_username: jekyllrb
github_username:  hongdinggao

